name: nst
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1q
  - python=3.9.13
  - readline=8.1.2
  - setuptools=63.4.1
  - sqlite=3.39.2
  - tk=8.6.12
  - tzdata=2022c
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.2.0
    - astunparse==1.6.3
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - cycler==0.11.0
    - flatbuffers==2.0.7
    - fonttools==4.37.3
    - gast==0.4.0
    - google-auth==2.11.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.49.1
    - h5py==3.7.0
    - idna==3.4
    - importlib-metadata==4.12.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - numpy==1.23.2
    - oauthlib==3.2.1
    - opt-einsum==3.3.0
    - packaging==21.3
    - pillow==9.2.0
    - pip==22.2.2
    - protobuf==3.19.5
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - six==1.16.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.0.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.8.1
